### ISSUE TITLE
HP ALM compatibility?

### ISSUE THREAD

**Issue by Petikoch** [okean/alm-rest-api#2]
Hi @okean , 

do you know how compatible your library is to the various ALM versions? 12.0, 12.2, 12.5

We are currently on 12.0

Best regards!
Peti

**Comment by okean** [comment]
Hi,

The api client has been written against 12.2 documentation, provided by HP. The current project I'm involved in uses ALM 12.01 and we haven't faced any issues.

**Comment by Petikoch** [comment]
Sounds promising... thanks a lot for your reply.
